baseURL = "https://feivaoco.github.io/"
title = "Feiv's Moon"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Copyright 2023, FeivMoon"

[assets]
    favicon = "/favicon.ico"

[params]
    description = "Página blog para públicar mis proyectos con el seudónimo de FeivMoon. Feiv's Moon."      # Your meta description of the site
    header_title = "Feiv's Moon"                 
    header_subtitle = "Blog de FeivMoon" 
    home_image = "/img/helpy.png" 
    
    favicon = true
    recent_posts = 15                           
    mainSections = ["posts", "post", "blog"]   
    
   
        
    [params.style]                             
        backgroundColor = "#242930"
        homeImageBorderColor = "#57cc8a"
        fontFamilyBase = "Helvetica Neue"        
        fontColor = "#57cc8a"
        

    [[params.social]]
        fa_icon = "fab fa-itch-io fa-2x"
        href = "https://feivvydiadev.itch.io"      
    [[params.social]]
        name = "Mi github"
        fa_icon = "fab fa-github fa-2x"          
        href = "https://github.com/feivaoco"
    [[params.social]]
        fa_icon = "fab fa-spotify fa-2x"
        href = "https://open.spotify.com/intl-es/artist/10yCFAEVhf5zWitCCcPAPf"
    [[params.social]]
        fa_icon = "fab fa-soundcloud fa-2x"
        href = "https://soundcloud.com/user-322543212"
    [[params.social]]
        fa_icon = "fab fa-twitter fa-2x"
        href = "https://twitter.com/Feivaco69"
    

        