baseURL = "https://feivaoco.github.io/"
title = "Feiv's Moon"


paginate = 15

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "Sobre mí"
    url = "/about/"
    weight = 3

[params]
  author = "FeivMoon"
  avatar = "helpy.png"
  description = "Blog para publicar mis proyectos"
  menu_item_separator = " | "
  [[params.social]]
    icon = "mail"
    name = "contact"
    url = "mailto:feivmoon.projects@gmail.com"
  [[params.social]]
    icon = "link"
    name = "itchio"
    url = "https://feivvydiadev.itch.io/"
  [[params.social]]
    icon = "github"
    name = "github"
    url = "https://github.com/feivaoco"
  [[params.social]]
    icon = "music"
    name = "bandcamp"
    url = "https://feivmoon.bandcamp.com"
  [[params.social]]
    icon = "music"
    name = "spotify"
    url = "https://open.spotify.com/intl-es/artist/10yCFAEVhf5zWitCCcPAPf"    
  [[params.social]]
    icon = "music"
    name = "soundcloud"
    url = "https://soundcloud.com/user-322543212"
  [[params.social]]
    icon = "youtube"
    name = "youtube"
    url = "https://www.youtube.com/channel/UC3beyJaNq77kjC3sGFk52dQ"
  [[params.social]]
    icon = "twitter"
    name = "twitter"
    url = "https://twitter.com/Feivaco69"

  

  
  # Default theme
  #[params.style]
  #  darkestColor = "#242930"
  #  darkColor = "#353b43"
  #  lightColor = "#afbac4"
  #  lightestColor = "#ffffff"
  #  primaryColor = "#57cc8a"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"
  #  primaryColor = "#dad865"

  # Red theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  lightColor = "#d6d6d6"
  #  lightestColor = "#d3d3d3"
  #  primaryColor = "#ffffff"
